import { createMemo, createSignal } from "solid-js";

import { Label } from "../../../../Lib/Fundamentals/Input/Label/Label";
import { TextArea } from "../../../../Lib/Fundamentals/Input/TextArea/TextArea";
import { PageLabelCaption } from "../../PageComponents/LabelCaption/LabelCaption";
import { PageVariants } from "../../PageComponents/Variants/Variants";
import {
    PageTextFieldContent,
    computePageTextFieldTextStyle,
} from "../../StyledComponents/TextFieldContent/TextFieldContent";
import { PageTextFieldPlaceholder } from "../../StyledComponents/TextFieldPlaceholder/TextFieldPlaceholder";
import { PageTooltipContent } from "../../StyledComponents/TooltipContent/TooltipContent";

import { FIELD_GAP, FIELD_PADDING } from "../../StyledComponents/TextFieldContent/TextFieldContent.css";

const FIELD_WIDTH = 260;
const FIXED_HEIGHT = 110;
const MIN_ROWS = 2;
const MAX_ROWS = 8;
const LONG_TEXT = "One line.\nTwo lines.\nThree lines, and the box has to have grown by now.";
const REVIEW_LIMIT = 80;

export const TextAreaPage = () => {
    const fixedSignal = createSignal("");
    const growingSignal = createSignal("");
    const cappedSignal = createSignal(LONG_TEXT);
    const readOnlySignal = createSignal("Generated by the server,\nacross two lines.");
    const disabledSignal = createSignal("Cannot be edited");
    const reachableSignal = createSignal("Cannot be edited either");
    const erroredSignal = createSignal("Too short");
    const labelledSignal = createSignal("");

    const getVariants = createMemo(() => {
        return [
            {
                name: "Fixed height",
                readout: () => `length: ${fixedSignal[0]().length} — the painter sizes the box and it stays put`,
                component: () => (
                    <TextArea
                        valueSignal={fixedSignal}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getAriaLabel={() => "Notes"}
                        computeTextStyle={computePageTextFieldTextStyle}
                        renderContent={(getFlags) => (
                            <PageTextFieldContent
                                getFlags={getFlags}
                                getWidth={() => FIELD_WIDTH}
                                getHeight={() => FIXED_HEIGHT}
                            />
                        )}
                        renderPlaceholder={(getFlags) => (
                            <PageTextFieldPlaceholder getFlags={getFlags} getIsTopAligned={() => true}>
                                Notes
                            </PageTextFieldPlaceholder>
                        )}
                    />
                ),
            },
            {
                name: "Auto-sizing",
                readout: () =>
                    `length: ${growingSignal[0]().length} — grows from ${MIN_ROWS} rows with no ceiling, so it never scrolls`,
                component: () => (
                    <TextArea
                        valueSignal={growingSignal}
                        getIsAutoSizing={() => true}
                        getMinRows={() => MIN_ROWS}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getAriaLabel={() => "Message"}
                        computeTextStyle={computePageTextFieldTextStyle}
                        renderContent={(getFlags) => (
                            <PageTextFieldContent
                                getFlags={getFlags}
                                getWidth={() => FIELD_WIDTH}
                                getIsStretched={() => true}
                            />
                        )}
                        renderPlaceholder={(getFlags) => (
                            <PageTextFieldPlaceholder getFlags={getFlags} getIsTopAligned={() => true}>
                                Type across several lines
                            </PageTextFieldPlaceholder>
                        )}
                    />
                ),
            },
            {
                name: "Auto-sizing, capped",
                readout: () => `length: ${cappedSignal[0]().length} — stops growing at ${MAX_ROWS} rows and scrolls`,
                component: () => (
                    <TextArea
                        valueSignal={cappedSignal}
                        getIsAutoSizing={() => true}
                        getMinRows={() => MIN_ROWS}
                        getMaxRows={() => MAX_ROWS}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getAriaLabel={() => "Description"}
                        computeTextStyle={computePageTextFieldTextStyle}
                        renderContent={(getFlags) => (
                            <PageTextFieldContent
                                getFlags={getFlags}
                                getWidth={() => FIELD_WIDTH}
                                getIsStretched={() => true}
                            />
                        )}
                    />
                ),
            },
            {
                name: "Read-only",
                readout: () => `length: ${readOnlySignal[0]().length} — selectable and copyable, never editable`,
                component: () => (
                    <TextArea
                        valueSignal={readOnlySignal}
                        getIsReadOnly={() => true}
                        getIsAutoSizing={() => true}
                        getMinRows={() => MIN_ROWS}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getAriaLabel={() => "Read-only notes"}
                        computeTextStyle={computePageTextFieldTextStyle}
                        renderContent={(getFlags) => (
                            <PageTextFieldContent
                                getFlags={getFlags}
                                getWidth={() => FIELD_WIDTH}
                                getIsStretched={() => true}
                            />
                        )}
                    />
                ),
            },
            {
                name: "Disabled",
                readout: () => `length: ${disabledSignal[0]().length}`,
                component: () => (
                    <TextArea
                        valueSignal={disabledSignal}
                        getIsDisabled={() => true}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getAriaLabel={() => "Disabled notes"}
                        computeTextStyle={computePageTextFieldTextStyle}
                        renderContent={(getFlags) => (
                            <PageTextFieldContent
                                getFlags={getFlags}
                                getWidth={() => FIELD_WIDTH}
                                getHeight={() => FIXED_HEIGHT}
                            />
                        )}
                    />
                ),
            },
            {
                name: "Disabled + reachable",
                readout: () => `length: ${reachableSignal[0]().length}`,
                component: () => (
                    <TextArea
                        valueSignal={reachableSignal}
                        getIsDisabled={() => true}
                        getIsReachableWhenDisabled={() => true}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getAriaLabel={() => "Disabled but reachable notes"}
                        computeTextStyle={computePageTextFieldTextStyle}
                        renderContent={(getFlags) => (
                            <PageTextFieldContent
                                getFlags={getFlags}
                                getWidth={() => FIELD_WIDTH}
                                getHeight={() => FIXED_HEIGHT}
                            />
                        )}
                        getTooltipDefs={() => ({
                            getPlacement: () => ({ x: "center", y: "top-out" }),
                            getOffset: () => ({ x: 0, y: 5 }),
                            renderContent: (getVisibilityTarget, getTransitionDurationMs) => (
                                <PageTooltipContent
                                    getVisibilityTarget={getVisibilityTarget}
                                    getTransitionDurationMs={getTransitionDurationMs}
                                >
                                    Focusable so this tooltip can be read, but typing must leave the value alone.
                                </PageTooltipContent>
                            ),
                        })}
                    />
                ),
            },
            {
                name: "Error",
                readout: () =>
                    `length: ${erroredSignal[0]().length} — fewer than ${REVIEW_LIMIT} characters is an error`,
                component: () => (
                    <TextArea
                        valueSignal={erroredSignal}
                        getIsAutoSizing={() => true}
                        getMinRows={() => MIN_ROWS}
                        getMaxRows={() => MAX_ROWS}
                        getHasError={() => erroredSignal[0]().length < REVIEW_LIMIT}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getAriaLabel={() => "Review"}
                        computeTextStyle={computePageTextFieldTextStyle}
                        renderContent={(getFlags) => (
                            <PageTextFieldContent
                                getFlags={getFlags}
                                getWidth={() => FIELD_WIDTH}
                                getIsStretched={() => true}
                            />
                        )}
                    />
                ),
            },
            {
                name: "In a Label",
                readout: () => `length: ${labelledSignal[0]().length}`,
                component: () => (
                    <Label getDir={() => "column"} getGap={() => 5}>
                        <PageLabelCaption>Bio</PageLabelCaption>

                        <TextArea
                            valueSignal={labelledSignal}
                            getIsAutoSizing={() => true}
                            getMinRows={() => MIN_ROWS}
                            getMaxRows={() => MAX_ROWS}
                            getPadding={() => FIELD_PADDING}
                            getGap={() => FIELD_GAP}
                            computeTextStyle={computePageTextFieldTextStyle}
                            renderContent={(getFlags) => (
                                <PageTextFieldContent
                                    getFlags={getFlags}
                                    getWidth={() => FIELD_WIDTH}
                                    getIsStretched={() => true}
                                />
                            )}
                        />
                    </Label>
                ),
            },
        ];
    });

    return <PageVariants getItems={getVariants} />;
};
