import { createMemo, createSignal } from "solid-js";

import { Button } from "../../../../Lib/Fundamentals/Button/Button";
import { Label } from "../../../../Lib/Fundamentals/Input/Label/Label";
import { TextInput } from "../../../../Lib/Fundamentals/Input/TextInput/TextInput";
import { PageLabelCaption } from "../../PageComponents/LabelCaption/LabelCaption";
import { PageVariants } from "../../PageComponents/Variants/Variants";
import { PageTextInputAdornment } from "../../StyledComponents/TextInputAdornment/TextInputAdornment";
import {
    PageTextInputContent,
    computePageTextInputTextStyle,
} from "../../StyledComponents/TextInputContent/TextInputContent";
import { PageTextInputPlaceholder } from "../../StyledComponents/TextInputPlaceholder/TextInputPlaceholder";
import { PageTooltipContent } from "../../StyledComponents/TooltipContent/TooltipContent";

import { FIELD_GAP, FIELD_PADDING } from "../../StyledComponents/TextInputContent/TextInputContent.css";

const PIN_LENGTH = 6;

export const TextInputPage = () => {
    const defaultSignal = createSignal("");
    const passwordSignal = createSignal("");
    const readOnlySignal = createSignal("Generated by the server");
    const disabledSignal = createSignal("Cannot be edited");
    const reachableSignal = createSignal("Cannot be edited either");
    const erroredSignal = createSignal("not-an-email");
    const labelledSignal = createSignal("");
    const codeSignal = createSignal("");
    const pinSignal = createSignal("");
    const amountSignal = createSignal("");
    const quantitySignal = createSignal("10");
    const revealSignal = createSignal(false);

    const getVariants = createMemo(() => {
        return [
            {
                name: "Default",
                readout: () => `value: "${defaultSignal[0]()}"`,
                component: () => (
                    <TextInput
                        valueSignal={defaultSignal}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getAriaLabel={() => "Your name"}
                        computeTextStyle={computePageTextInputTextStyle}
                        renderContent={(getFlags) => <PageTextInputContent getFlags={getFlags} />}
                        renderPlaceholder={(getFlags) => (
                            <PageTextInputPlaceholder getFlags={getFlags}>Your name</PageTextInputPlaceholder>
                        )}
                    />
                ),
            },
            {
                name: "Transforming setter",
                readout: () => `value: "${codeSignal[0]()}" — type lowercase mid-string, the caret must not jump`,
                component: () => (
                    <TextInput
                        valueSignal={codeSignal}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getAriaLabel={() => "Coupon code"}
                        onInput={(value) => {
                            codeSignal[1](value.toLocaleUpperCase());
                        }}
                        computeTextStyle={computePageTextInputTextStyle}
                        renderContent={(getFlags) => <PageTextInputContent getFlags={getFlags} />}
                        renderPlaceholder={(getFlags) => (
                            <PageTextInputPlaceholder getFlags={getFlags}>
                                Coupon code (upper-cased)
                            </PageTextInputPlaceholder>
                        )}
                    />
                ),
            },
            {
                name: "Refusing setter",
                readout: () => `value: "${pinSignal[0]()}" — letters are refused, ${PIN_LENGTH} digits max`,
                component: () => (
                    <TextInput
                        valueSignal={pinSignal}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getAriaLabel={() => "PIN"}
                        getInputMode={() => "numeric"}
                        getHasError={() => pinSignal[0]().length > 0 && pinSignal[0]().length < PIN_LENGTH}
                        onInput={(value) => {
                            pinSignal[1](value.replace(/\D/g, "").slice(0, PIN_LENGTH));
                        }}
                        computeTextStyle={computePageTextInputTextStyle}
                        renderContent={(getFlags) => <PageTextInputContent getFlags={getFlags} />}
                        renderPlaceholder={(getFlags) => (
                            <PageTextInputPlaceholder getFlags={getFlags}>Digits only</PageTextInputPlaceholder>
                        )}
                    />
                ),
            },
            {
                name: "Password",
                readout: () => `value: "${passwordSignal[0]()}" | revealed: ${revealSignal[0]()}`,
                component: () => (
                    <TextInput
                        valueSignal={passwordSignal}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getType={() => (revealSignal[0]() ? "text" : "password")}
                        getAriaLabel={() => "Password"}
                        getAutoComplete={() => "current-password"}
                        computeTextStyle={computePageTextInputTextStyle}
                        renderContent={(getFlags) => <PageTextInputContent getFlags={getFlags} />}
                        renderPlaceholder={(getFlags) => (
                            <PageTextInputPlaceholder getFlags={getFlags}>Password</PageTextInputPlaceholder>
                        )}
                        renderTrailing={() => (
                            <Button
                                onClick={() => {
                                    revealSignal[1]((prev) => !prev);
                                }}
                                renderContent={(getFlags) => (
                                    <PageTextInputAdornment getFlags={getFlags}>
                                        {revealSignal[0]() ? "Hide" : "Show"}
                                    </PageTextInputAdornment>
                                )}
                            />
                        )}
                    />
                ),
            },
            {
                name: "Both adornments",
                readout: () => `value: "${amountSignal[0]()}"`,
                component: () => (
                    <TextInput
                        valueSignal={amountSignal}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getAriaLabel={() => "Amount"}
                        getInputMode={() => "decimal"}
                        computeTextStyle={computePageTextInputTextStyle}
                        renderContent={(getFlags) => <PageTextInputContent getFlags={getFlags} />}
                        renderPlaceholder={(getFlags) => (
                            <PageTextInputPlaceholder getFlags={getFlags}>0.00</PageTextInputPlaceholder>
                        )}
                        renderLeading={(getFlags) => (
                            <PageTextInputAdornment getFlags={getFlags}>USD</PageTextInputAdornment>
                        )}
                        renderTrailing={() => (
                            <Button
                                getIsDisabled={() => amountSignal[0]() === ""}
                                onClick={() => {
                                    amountSignal[1]("");
                                }}
                                renderContent={(getFlags) => (
                                    <PageTextInputAdornment getFlags={getFlags}>Clear</PageTextInputAdornment>
                                )}
                            />
                        )}
                    />
                ),
            },
            {
                name: "Number",
                readout: () => `value: "${quantitySignal[0]()}" — arrows step by 5, no spinner buttons`,
                component: () => (
                    <TextInput
                        valueSignal={quantitySignal}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getType={() => "number"}
                        getAriaLabel={() => "Quantity"}
                        getMin={() => 0}
                        getMax={() => 100}
                        getStep={() => 5}
                        computeTextStyle={computePageTextInputTextStyle}
                        renderContent={(getFlags) => <PageTextInputContent getFlags={getFlags} />}
                    />
                ),
            },
            {
                name: "Read-only",
                readout: () => `value: "${readOnlySignal[0]()}" — selectable and copyable, never editable`,
                component: () => (
                    <TextInput
                        valueSignal={readOnlySignal}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getIsReadOnly={() => true}
                        getAriaLabel={() => "Read-only field"}
                        computeTextStyle={computePageTextInputTextStyle}
                        renderContent={(getFlags) => <PageTextInputContent getFlags={getFlags} />}
                    />
                ),
            },
            {
                name: "Disabled",
                readout: () => `value: "${disabledSignal[0]()}"`,
                component: () => (
                    <TextInput
                        valueSignal={disabledSignal}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getIsDisabled={() => true}
                        getAriaLabel={() => "Disabled field"}
                        computeTextStyle={computePageTextInputTextStyle}
                        renderContent={(getFlags) => <PageTextInputContent getFlags={getFlags} />}
                    />
                ),
            },
            {
                name: "Disabled + reachable",
                readout: () => `value: "${reachableSignal[0]()}"`,
                component: () => (
                    <TextInput
                        valueSignal={reachableSignal}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getIsDisabled={() => true}
                        getIsReachableWhenDisabled={() => true}
                        getAriaLabel={() => "Disabled but reachable field"}
                        computeTextStyle={computePageTextInputTextStyle}
                        renderContent={(getFlags) => <PageTextInputContent getFlags={getFlags} />}
                        getTooltipDefs={() => ({
                            getPlacement: () => ({ x: "center", y: "top-out" }),
                            getOffset: () => ({ x: 0, y: 5 }),
                            renderContent: (getVisibilityTarget, getTransitionDurationMs) => (
                                <PageTooltipContent
                                    getVisibilityTarget={getVisibilityTarget}
                                    getTransitionDurationMs={getTransitionDurationMs}
                                >
                                    Focusable so this tooltip can be read, but typing must leave the value alone.
                                </PageTooltipContent>
                            ),
                        })}
                    />
                ),
            },
            {
                name: "Error",
                readout: () => `value: "${erroredSignal[0]()}"`,
                component: () => (
                    <TextInput
                        valueSignal={erroredSignal}
                        getPadding={() => FIELD_PADDING}
                        getGap={() => FIELD_GAP}
                        getType={() => "email"}
                        getHasError={() => !erroredSignal[0]().includes("@")}
                        getAriaLabel={() => "Email"}
                        getAutoComplete={() => "email"}
                        computeTextStyle={computePageTextInputTextStyle}
                        renderContent={(getFlags) => <PageTextInputContent getFlags={getFlags} />}
                    />
                ),
            },
            {
                name: "In a Label",
                readout: () => `value: "${labelledSignal[0]()}"`,
                component: () => (
                    <Label getDir={() => "column"} getGap={() => 5}>
                        <PageLabelCaption>Display name</PageLabelCaption>

                        <TextInput
                            valueSignal={labelledSignal}
                            getPadding={() => FIELD_PADDING}
                            getGap={() => FIELD_GAP}
                            computeTextStyle={computePageTextInputTextStyle}
                            renderContent={(getFlags) => <PageTextInputContent getFlags={getFlags} />}
                        />
                    </Label>
                ),
            },
        ];
    });

    return <PageVariants getItems={getVariants} />;
};
